### PR TITLE
Webpack build process upgraded

### PR DESCRIPTION
**Pull request by CaseyHillers**
yarn run dev - run http server at localhost:8080
yarn run build - IE11 compatible
yarn run lint - clean  code check
yarn run test - run full test suite
yarn run e2e - e2e test suite
yarn run unit - unit test suite

Let me know if there's any issues.

### CODE REVIEW

**Comment by randli** [comment]
worked on my machine

**Review by randli — APPROVED** [review]
Works nicely

**Comment by ciarafitz** [comment]
our code base is not up-to-date with the linter

**Comment by ciarafitz** [comment]
Almost all is indentation errors

**Pull request merged**
